{
 "title": "NetFlow for Mininet Visualization Tool.",
 "description": "This dashboard link together Prometheus flows and Postgres, in order to give information about the state of the Mininet's Network.",
 "tags": [ "Mininet" ],
 "time": { "from": "2024-02-24T17:29:57.037Z", "to": "2024-02-24T17:33:20.332Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Most Volume of Traffic, by src_dst (KB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT src_addr, dst_addr, octets FROM flows;"
    }
   ]
  },
  {
   "title": "TCP/UDP Traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'UDP' as Protocol, COUNT(tos) as Count FROM flows WHERE tos =  0 GROUP BY tos\nUNION ALL\nSELECT 'TCP', COUNT(tos) FROM flows WHERE tos =  16 GROUP BY tos;"
    }
   ]
  },
  {
   "title": "Flow Most Popular.",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT src_addr, dst_addr, pkt_count FROM flows ORDER BY pkt_count DESC LIMIT 50;  "
    }
   ]
  },
  {
   "title": "VFLOW Packet Decoded",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vflow_netflowv5_decoded_packets",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VFLOW Packet Received.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vflow_netflowv5_udp_packets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dst. Most Popular",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT dst_addr FROM flows ORDER BY pkt_count ASC LIMIT 1;  "
    }
   ]
  },
  {
   "title": "Src. Most Popular",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT src_addr FROM flows ORDER BY pkt_count DESC LIMIT 1;  "
    }
   ]
  },
  {
   "title": "Packet Received.",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "vflow_netflowv5_udp_packets", "legendFormat": "__auto" }
   ]
  }
 ]
}